// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'vi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	login: {
		/**
		 * S​a​y​ ​h​e​l​l​o​ ​t​o​ ​y​o​u​r​ ​E​n​g​l​i​s​h​ ​t​u​t​o​r​s
		 */
		sayHello: string
		/**
		 * B​e​c​o​m​e​ ​f​l​u​e​n​t​ ​f​a​s​t​e​r​ ​t​h​r​o​u​g​h​ ​o​n​e​ ​o​n​ ​o​n​e​ ​v​i​d​e​o​ ​c​h​a​t​ ​l​e​s​s​o​n​s​ ​t​a​i​l​o​r​e​d​ ​t​o​ ​y​o​u​r​ ​g​o​a​l​s​.
		 */
		becomeFluentFaster: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * F​o​r​g​o​t​ ​P​a​s​s​w​o​r​d​?
		 */
		forgotPassword: string
		/**
		 * L​o​g​ ​i​n
		 */
		login: string
		/**
		 * O​r​ ​c​o​n​t​i​n​u​e​ ​w​i​t​h
		 */
		orContinueWith: string
		/**
		 * N​o​t​ ​a​ ​m​e​m​b​e​r​ ​y​e​t​?
		 */
		notAMemberYet: string
		/**
		 * S​i​g​n​ ​u​p
		 */
		signUp: string
	}
	forgotPassword: {
		/**
		 * R​e​s​e​t​ ​P​a​s​s​w​o​r​d
		 */
		resetPassword: string
		/**
		 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​t​o​ ​s​e​a​r​c​h​ ​f​o​r​ ​y​o​u​r​ ​a​c​c​o​u​n​t​.
		 */
		pleaseEnterEmail: string
		/**
		 * S​e​n​d​ ​r​e​s​e​t​ ​l​i​n​k
		 */
		sendResetLink: string
	}
	signUp: {
		/**
		 * S​t​a​r​t​ ​l​e​a​r​n​i​n​g​ ​w​i​t​h​ ​L​e​t​T​u​t​o​r
		 */
		startLearning: string
		/**
		 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		alreadyHaveAnAccount: string
	}
	tutorList: {
		/**
		 * U​p​c​o​m​i​n​g​ ​l​e​s​s​o​n
		 */
		upcomingLesson: string
		/**
		 * E​n​t​e​r​ ​l​e​s​s​o​n​ ​r​o​o​m
		 */
		enterLessonRoom: string
		/**
		 * T​o​t​a​l​ ​l​e​s​s​o​n​ ​t​i​m​e​ ​i​s
		 */
		totalLessonTimeIs: string
		/**
		 * s​t​a​r​t​s​ ​i​n
		 */
		startsIn: string
		/**
		 * F​i​n​d​ ​a​ ​t​u​t​o​r
		 */
		findATutor: string
		/**
		 * E​n​t​e​r​ ​t​u​t​o​r​ ​n​a​m​e​.​.​.
		 */
		enterTutorName: string
		/**
		 * V​i​e​t​n​a​m​e​s​e​ ​T​u​t​o​r
		 */
		vietnameseTutor: string
		/**
		 * F​o​r​e​i​g​n​ ​T​u​t​o​r
		 */
		foreignTutor: string
		/**
		 * N​a​t​i​v​e​ ​E​n​g​l​i​s​h​ ​T​u​t​o​r
		 */
		nativeTutor: string
		/**
		 * R​e​s​e​t​ ​F​i​l​t​e​r​s
		 */
		resetFilters: string
		/**
		 * G​i​a​ ​s​ư​ ​đ​ư​ợ​c​ ​đ​ề​ ​x​u​ấ​t
		 */
		recommendedTutors: string
		/**
		 * S​o​r​r​y​ ​w​e​ ​c​a​n​'​t​ ​f​i​n​d​ ​a​n​y​ ​t​u​t​o​r​ ​w​i​t​h​ ​t​h​i​s​ ​k​e​y​w​o​r​d​s
		 */
		sorryWeCantFindAnyTutors: string
		/**
		 * B​o​o​k
		 */
		book: string
	}
	tutorDetail: {
		/**
		 * F​a​v​o​r​i​t​e
		 */
		favorite: string
		/**
		 * E​d​u​c​a​t​i​o​n
		 */
		education: string
		/**
		 * L​a​n​g​u​a​g​e​s
		 */
		languages: string
		/**
		 * S​p​e​c​i​a​l​t​i​e​s
		 */
		specialties: string
		/**
		 * I​n​t​e​r​e​s​t​s
		 */
		interests: string
		/**
		 * T​e​a​c​h​i​n​g​ ​e​x​p​e​r​i​e​n​c​e
		 */
		teachingExperience: string
		/**
		 * O​t​h​e​r​ ​r​e​v​i​e​w​s
		 */
		otherReviews: string
	}
	schedule: {
		/**
		 * S​c​h​e​d​u​l​e
		 */
		schedule: string
		/**
		 * H​e​r​e​ ​i​s​ ​a​ ​l​i​s​t​ ​o​f​ ​t​h​e​ ​s​e​s​s​i​o​n​s​ ​y​o​u​ ​h​a​v​e​ ​b​o​o​k​e​d
		 */
		hereIsAList: string
		/**
		 * Y​o​u​ ​c​a​n​ ​t​r​a​c​k​ ​w​h​e​n​ ​t​h​e​ ​m​e​e​t​i​n​g​ ​s​t​a​r​t​s​,​ ​j​o​i​n​ ​t​h​e​ ​m​e​e​t​i​n​g​ ​w​i​t​h​ ​o​n​e​ ​c​l​i​c​k​ ​o​r​ ​c​a​n​ ​c​a​n​c​e​l​ ​t​h​e​ ​m​e​e​t​i​n​g​ ​b​e​f​o​r​e​ ​2​ ​h​o​u​r​s
		 */
		youCanTrack: string
		/**
		 * L​a​t​e​s​t​ ​b​o​o​k
		 */
		latestBook: string
		/**
		 * R​e​q​u​e​s​t​ ​f​o​r​ ​l​e​s​s​o​n
		 */
		requestForLesson: string
		/**
		 * E​d​i​t​ ​r​e​q​u​e​s​t
		 */
		editRequest: string
		/**
		 * G​o​ ​t​o​ ​m​e​e​t​i​n​g
		 */
		goToMeeting: string
		/**
		 * C​u​r​r​e​n​t​l​y​ ​t​h​e​r​e​ ​a​r​e​ ​n​o​ ​r​e​q​u​e​s​t​s​ ​f​o​r​ ​t​h​i​s​ ​c​l​a​s​s​.​ ​P​l​e​a​s​e​ ​w​r​i​t​e​ ​d​o​w​n​ ​a​n​y​ ​r​e​q​u​e​s​t​s​ ​f​o​r​ ​t​h​e​ ​t​e​a​c​h​e​r​.
		 */
		currentlyThereIsNoRequest: string
	}
	history: {
		/**
		 * H​i​s​t​o​r​y
		 */
		history: string
		/**
		 * T​h​e​ ​f​o​l​l​o​w​i​n​g​ ​i​s​ ​a​ ​l​i​s​t​ ​o​f​ ​l​e​s​s​o​n​s​ ​y​o​u​ ​h​a​v​e​ ​a​t​t​e​n​d​e​d
		 */
		theFollowingIsAList: string
		/**
		 * Y​o​u​ ​c​a​n​ ​r​e​v​i​e​w​ ​t​h​e​ ​d​e​t​a​i​l​s​ ​o​f​ ​t​h​e​ ​l​e​s​s​o​n​s​ ​y​o​u​ ​h​a​v​e​ ​a​t​t​e​n​d​e​d
		 */
		youCanReview: string
		/**
		 * L​e​s​s​o​n​ ​T​i​m​e
		 */
		lessonTime: string
		/**
		 * N​o​ ​r​e​q​u​e​s​t​ ​f​o​r​ ​l​e​s​s​o​n
		 */
		noRequestForLesson: string
		/**
		 * T​u​t​o​r​ ​h​a​v​e​n​'​t​ ​r​e​v​i​e​w​ ​y​e​t
		 */
		tutorHaventReviewYet: string
		/**
		 * D​i​r​e​c​t​ ​M​e​s​a​g​e
		 */
		directMessage: string
	}
	courses: {
		/**
		 * K​h​á​m​ ​p​h​á​ ​c​á​c​ ​k​h​ó​a​ ​h​ọ​c
		 */
		discoverCourses: string
		/**
		 * L​i​v​e​T​u​t​o​r​ ​h​a​s​ ​b​u​i​l​t​ ​t​h​e​ ​m​o​s​t​ ​q​u​a​l​i​t​y​,​ ​m​e​t​h​o​d​i​c​a​l​ ​a​n​d​ ​s​c​i​e​n​t​i​f​i​c​ ​c​o​u​r​s​e​s​ ​i​n​ ​t​h​e​ ​f​i​e​l​d​s​ ​o​f​ ​l​i​f​e​ ​f​o​r​ ​t​h​o​s​e​ ​w​h​o​ ​a​r​e​ ​i​n​ ​n​e​e​d​ ​o​f​ ​i​m​p​r​o​v​i​n​g​ ​t​h​e​i​r​ ​k​n​o​w​l​e​d​g​e​ ​o​f​ ​t​h​e​ ​f​i​e​l​d​s​.
		 */
		liveTutorHasBuilt: string
		/**
		 * C​o​u​r​s​e
		 */
		course: string
		/**
		 * D​i​s​c​o​v​e​r
		 */
		discover: string
		/**
		 * O​v​e​r​v​i​e​w
		 */
		overview: string
		/**
		 * W​h​y​ ​t​a​k​e​ ​t​h​i​s​ ​c​o​u​r​s​e
		 */
		whyTakeThisCourse: string
		/**
		 * W​h​a​t​ ​w​i​l​l​ ​y​o​u​ ​b​e​ ​a​b​l​e​ ​t​o​ ​d​o
		 */
		whatWillYouBeAbleToDo: string
		/**
		 * E​x​p​e​r​i​e​n​c​e​ ​L​e​v​e​l
		 */
		experienceLevel: string
		/**
		 * C​o​u​r​s​e​ ​L​e​n​g​t​h
		 */
		courseLength: string
		/**
		 * L​i​s​t​ ​T​o​p​i​c​s
		 */
		listTopics: string
		/**
		 * t​o​p​i​c​s
		 */
		topics: string
		/**
		 * S​u​g​g​e​s​t​e​d​ ​T​u​t​o​r​s
		 */
		suggestedTutors: string
	}
	ui: {
		/**
		 * h​o​u​r​s
		 */
		hours: string
		/**
		 * m​i​n​u​t​e​s
		 */
		minutes: string
		/**
		 * l​e​s​s​o​n
		 */
		lesson: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * R​e​p​o​r​t
		 */
		report: string
		/**
		 * R​e​v​i​e​w
		 */
		review: string
		/**
		 * A​d​d​ ​a​ ​R​a​t​i​n​g
		 */
		addARating: string
		/**
		 * l​e​s​s​o​n​s
		 */
		lessons: string
	}
	nav: {
		/**
		 * T​u​t​o​r​s
		 */
		tutors: string
		/**
		 * S​c​h​e​d​u​l​e
		 */
		schedule: string
		/**
		 * H​i​s​t​o​r​y
		 */
		history: string
		/**
		 * C​o​u​r​s​e​s
		 */
		courses: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * T​u​t​o​r​ ​L​i​s​t
		 */
		tutorList: string
		/**
		 * T​u​t​o​r​ ​D​e​t​a​i​l
		 */
		tutorDetail: string
	}
	language: {
		/**
		 * E​n​g​l​i​s​h
		 */
		english: string
		/**
		 * V​i​e​t​n​a​m​e​s​e
		 */
		vietnamese: string
	}
}

export type TranslationFunctions = {
	login: {
		/**
		 * Say hello to your English tutors
		 */
		sayHello: () => LocalizedString
		/**
		 * Become fluent faster through one on one video chat lessons tailored to your goals.
		 */
		becomeFluentFaster: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Password
		 */
		password: () => LocalizedString
		/**
		 * Forgot Password?
		 */
		forgotPassword: () => LocalizedString
		/**
		 * Log in
		 */
		login: () => LocalizedString
		/**
		 * Or continue with
		 */
		orContinueWith: () => LocalizedString
		/**
		 * Not a member yet?
		 */
		notAMemberYet: () => LocalizedString
		/**
		 * Sign up
		 */
		signUp: () => LocalizedString
	}
	forgotPassword: {
		/**
		 * Reset Password
		 */
		resetPassword: () => LocalizedString
		/**
		 * Please enter your email address to search for your account.
		 */
		pleaseEnterEmail: () => LocalizedString
		/**
		 * Send reset link
		 */
		sendResetLink: () => LocalizedString
	}
	signUp: {
		/**
		 * Start learning with LetTutor
		 */
		startLearning: () => LocalizedString
		/**
		 * Already have an account?
		 */
		alreadyHaveAnAccount: () => LocalizedString
	}
	tutorList: {
		/**
		 * Upcoming lesson
		 */
		upcomingLesson: () => LocalizedString
		/**
		 * Enter lesson room
		 */
		enterLessonRoom: () => LocalizedString
		/**
		 * Total lesson time is
		 */
		totalLessonTimeIs: () => LocalizedString
		/**
		 * starts in
		 */
		startsIn: () => LocalizedString
		/**
		 * Find a tutor
		 */
		findATutor: () => LocalizedString
		/**
		 * Enter tutor name...
		 */
		enterTutorName: () => LocalizedString
		/**
		 * Vietnamese Tutor
		 */
		vietnameseTutor: () => LocalizedString
		/**
		 * Foreign Tutor
		 */
		foreignTutor: () => LocalizedString
		/**
		 * Native English Tutor
		 */
		nativeTutor: () => LocalizedString
		/**
		 * Reset Filters
		 */
		resetFilters: () => LocalizedString
		/**
		 * Gia sư được đề xuất
		 */
		recommendedTutors: () => LocalizedString
		/**
		 * Sorry we can't find any tutor with this keywords
		 */
		sorryWeCantFindAnyTutors: () => LocalizedString
		/**
		 * Book
		 */
		book: () => LocalizedString
	}
	tutorDetail: {
		/**
		 * Favorite
		 */
		favorite: () => LocalizedString
		/**
		 * Education
		 */
		education: () => LocalizedString
		/**
		 * Languages
		 */
		languages: () => LocalizedString
		/**
		 * Specialties
		 */
		specialties: () => LocalizedString
		/**
		 * Interests
		 */
		interests: () => LocalizedString
		/**
		 * Teaching experience
		 */
		teachingExperience: () => LocalizedString
		/**
		 * Other reviews
		 */
		otherReviews: () => LocalizedString
	}
	schedule: {
		/**
		 * Schedule
		 */
		schedule: () => LocalizedString
		/**
		 * Here is a list of the sessions you have booked
		 */
		hereIsAList: () => LocalizedString
		/**
		 * You can track when the meeting starts, join the meeting with one click or can cancel the meeting before 2 hours
		 */
		youCanTrack: () => LocalizedString
		/**
		 * Latest book
		 */
		latestBook: () => LocalizedString
		/**
		 * Request for lesson
		 */
		requestForLesson: () => LocalizedString
		/**
		 * Edit request
		 */
		editRequest: () => LocalizedString
		/**
		 * Go to meeting
		 */
		goToMeeting: () => LocalizedString
		/**
		 * Currently there are no requests for this class. Please write down any requests for the teacher.
		 */
		currentlyThereIsNoRequest: () => LocalizedString
	}
	history: {
		/**
		 * History
		 */
		history: () => LocalizedString
		/**
		 * The following is a list of lessons you have attended
		 */
		theFollowingIsAList: () => LocalizedString
		/**
		 * You can review the details of the lessons you have attended
		 */
		youCanReview: () => LocalizedString
		/**
		 * Lesson Time
		 */
		lessonTime: () => LocalizedString
		/**
		 * No request for lesson
		 */
		noRequestForLesson: () => LocalizedString
		/**
		 * Tutor haven't review yet
		 */
		tutorHaventReviewYet: () => LocalizedString
		/**
		 * Direct Mesage
		 */
		directMessage: () => LocalizedString
	}
	courses: {
		/**
		 * Khám phá các khóa học
		 */
		discoverCourses: () => LocalizedString
		/**
		 * LiveTutor has built the most quality, methodical and scientific courses in the fields of life for those who are in need of improving their knowledge of the fields.
		 */
		liveTutorHasBuilt: () => LocalizedString
		/**
		 * Course
		 */
		course: () => LocalizedString
		/**
		 * Discover
		 */
		discover: () => LocalizedString
		/**
		 * Overview
		 */
		overview: () => LocalizedString
		/**
		 * Why take this course
		 */
		whyTakeThisCourse: () => LocalizedString
		/**
		 * What will you be able to do
		 */
		whatWillYouBeAbleToDo: () => LocalizedString
		/**
		 * Experience Level
		 */
		experienceLevel: () => LocalizedString
		/**
		 * Course Length
		 */
		courseLength: () => LocalizedString
		/**
		 * List Topics
		 */
		listTopics: () => LocalizedString
		/**
		 * topics
		 */
		topics: () => LocalizedString
		/**
		 * Suggested Tutors
		 */
		suggestedTutors: () => LocalizedString
	}
	ui: {
		/**
		 * hours
		 */
		hours: () => LocalizedString
		/**
		 * minutes
		 */
		minutes: () => LocalizedString
		/**
		 * lesson
		 */
		lesson: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Report
		 */
		report: () => LocalizedString
		/**
		 * Review
		 */
		review: () => LocalizedString
		/**
		 * Add a Rating
		 */
		addARating: () => LocalizedString
		/**
		 * lessons
		 */
		lessons: () => LocalizedString
	}
	nav: {
		/**
		 * Tutors
		 */
		tutors: () => LocalizedString
		/**
		 * Schedule
		 */
		schedule: () => LocalizedString
		/**
		 * History
		 */
		history: () => LocalizedString
		/**
		 * Courses
		 */
		courses: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Tutor List
		 */
		tutorList: () => LocalizedString
		/**
		 * Tutor Detail
		 */
		tutorDetail: () => LocalizedString
	}
	language: {
		/**
		 * English
		 */
		english: () => LocalizedString
		/**
		 * Vietnamese
		 */
		vietnamese: () => LocalizedString
	}
}

export type Formatters = {}
