export type Tutor = {
  level: "HIGHER_BEGINNER";
  email: string;
  google: null | any;
  facebook: null | any;
  apple: null | any;
  avatar: string;
  name: string;
  country: string;
  phone: string;
  language: null | any;
  birthday: string;
  requestPassword: boolean;
  isActivated: boolean;
  isPhoneActivated: boolean;
  requireNote: null | any;
  timezone: number;
  phoneAuth: null | any;
  isPhoneAuthActivated: boolean;
  studySchedule: string;
  canSendMessage: boolean;
  isPublicRecord: boolean;
  caredByStaffId: null | any;
  zaloUserId: null | any;
  createdAt: string;
  updatedAt: string;
  deletedAt: null | any;
  studentGroupId: null | any;
  feedbacks: Feedback[];
  id: string;
  userId: string;
  video: string;
  bio: string;
  education: string;
  experience: string;
  profession: string;
  accent: null;
  targetStudent: "Advanced";
  interests: string;
  languages: "en" | null;
  specialties: string;
  resume: null;
  rating: number;
  isNative: null;
  youtubeVideoId: null;
  price: number;
  isOnline: boolean;
  isFavoriteTutor: boolean;
};

export type Feedback = {
  id: string;
  bookingId: string;
  firstId: string;
  secondId: string;
  rating: number;
  content: string;
  createdAt: string;
  updatedAt: string;
  firstInfo: {
    level: string;
    email: string;
    google: null | any;
    facebook: null | any;
    apple: null | any;
    avatar: string;
    name: string;
    country: string;
    phone: string;
    language: null | any;
    birthday: string;
    requestPassword: boolean;
    isActivated: boolean;
    isPhoneActivated: boolean;
    requireNote: null | any;
    timezone: number;
    phoneAuth: null | any;
    isPhoneAuthActivated: boolean;
    studySchedule: string;
    canSendMessage: boolean;
    isPublicRecord: boolean;
    caredByStaffId: null | any;
    zaloUserId: null | any;
    createdAt: string;
    updatedAt: string;
    deletedAt: null | any;
    studentGroupId: null | any;
  };
};

type TutorUser = {
  avatar: string;
  caredByStaffId: null | any;
  country: string;
  courses: any[];
  id: string;
  isPublicRecord: boolean;
  language: string;
  level: null | any;
  name: string;
  studentGroupId: null | any;
  zaloUserId: null | any;
};

export type TutorDetail = {
  User: TutorUser;
  accent: string;
  avgRating: number;
  bio: string;
  education?: string;
  experience?: string;
  interests: string;
  isFavorite: boolean;
  isNative: null;
  languages: string;
  profession: string;
  rating: null;
  specialties: string;
  targetStudent: string;
  totalFeedback: number;
  video: string;
  youtubeVideoId: null;
};
